apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginx1
  labels: 
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: sujatagoudar/mytomcat:1.0.5
  - name: myenkins
    image: nginx:1.14.2
